### ISSUE TITLE
Error when running python manage.py makemigrations

### ISSUE THREAD

**Issue by ghost** [Husseinfo/tracker#5]
TimeoutError: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond

**Comment by harshmalik** [comment]
Getting this error
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/Users/harshkumar1/Desktop/faceauth/tracker-master/tracker/mqtt.py", line 41, in run
    self.mqttc.connect(self.ip, self.port, 60)
  File "/Users/harshkumar1/Desktop/faceauth/lib/python3.6/site-packages/paho/mqtt/client.py", line 839, in connect
    return self.reconnect()
  File "/Users/harshkumar1/Desktop/faceauth/lib/python3.6/site-packages/paho/mqtt/client.py", line 962, in reconnect
    sock = socket.create_connection((self._host, self._port), source_address=(self._bind_address, 0))
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/socket.py", line 724, in create_connection
    raise err
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/socket.py", line 713, in create_connection
    sock.connect(sa)
TimeoutError: [Errno 60] Operation timed out

**Comment by Husseinfo** [comment]
#6
