### ISSUE TITLE
mqtt connection error

### ISSUE THREAD

**Issue by hussainaphroj** [Husseinfo/tracker#6]
Hi, 

Thank you very much for this project. I tried to setup on window laptop for learning purpose but it is failing due to this error:

Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Users\ahussain\AppData\Local\Programs\Python\Python36\lib\threading.py", line 916, in _bootstrap_inner
    self.run()
  File "F:\sabir\tracker\tracker\mqtt.py", line 41, in run
    self.mqttc.connect(self.ip, self.port, 60)
  File "C:\Users\ahussain\AppData\Local\Programs\Python\Python36\lib\site-packages\paho\mqtt\client.py", line 839, in connect
    return self.reconnect()
  File "C:\Users\ahussain\AppData\Local\Programs\Python\Python36\lib\site-packages\paho\mqtt\client.py", line 962, in reconnect
    sock = socket.create_connection((self._host, self._port), source_address=(self._bind_address, 0))
  File "C:\Users\ahussain\AppData\Local\Programs\Python\Python36\lib\socket.py", line 724, in create_connection
    raise err
  File "C:\Users\ahussain\AppData\Local\Programs\Python\Python36\lib\socket.py", line 713, in create_connection
    sock.connect(sa)
TimeoutError: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond

I have installed followings:

opencv-python==3.2.0.6
django==1.10.5
psycopg2==2.7.1
djangorestframework==3.9.0
numpy==1.12.1

pip install paho-mqtt python-etcd
pip install opencv-contrib-python
pip install django-sslserver
pip install pytz
pip install Pillow

Any help would be really appreciated.

Thanks,
Afroz

**Comment by Husseinfo** [comment]
you need to install mqtt server first
either on the raspberry or the windows host
