### ISSUE TITLE
recognizer = cv2.face.LBPHFaceRecognizer_create()

### ISSUE THREAD

**Issue by iHaagcom** [Husseinfo/tracker#9]
python .\manage.py makemigrations
C:\Program Files\Python38\lib\site-packages\numpy\_distributor_init.py:30: UserWarning: loaded more than 1 DLL from .libs:
C:\Program Files\Python38\lib\site-packages\numpy\.libs\libopenblas.NOIJJG62EMASZI6NYURL6JBKM4EVBGM7.gfortran-win_amd64.dll
C:\Program Files\Python38\lib\site-packages\numpy\.libs\libopenblas.PYQHXLVVQ7VESDPUVUADXEVJOBGHJPAY.gfortran-win_amd64.dll
  warnings.warn("loaded more than 1 DLL from .libs:\n%s" %
Traceback (most recent call last):
  File ".\manage.py", line 24, in <module>
    execute_from_command_line(sys.argv)
  File "C:\Program Files\Python38\lib\site-packages\django\core\management\__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "C:\Program Files\Python38\lib\site-packages\django\core\management\__init__.py", line 345, in execute
    settings.INSTALLED_APPS
  File "C:\Program Files\Python38\lib\site-packages\django\conf\__init__.py", line 82, in __getattr__
    self._setup(name)
  File "C:\Program Files\Python38\lib\site-packages\django\conf\__init__.py", line 69, in _setup
    self._wrapped = Settings(settings_module)
  File "C:\Program Files\Python38\lib\site-packages\django\conf\__init__.py", line 170, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "C:\Program Files\Python38\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\\Attendace_management_system-master\tracker-master\tracker\__init__.py", line 1, in <module>
    from tracker.recognition.recognizer import Recognizer
  File "C\Attendace_management_system-master\tracker-master\tracker\recognition\recognizer.py", line 10, in <module>
    recognizer = cv2.face.createLBPHFaceRecognizer()
AttributeError: module 'cv2.face' has no attribute 'createLBPHFaceRecognizer'

**Comment by Husseinfo** [comment]
OpenCV was removed already
